name: Flutter CI_CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.35.2"
          channel: "stable"

      - name: Ensure project structure
        run: flutter create .

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Launcher Icon
        run: flutter pub run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release \
          --dart-define=SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --dart-define=SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} \
          --dart-define=SUPABASE_FUNCTIONS_URL=${{ secrets.SUPABASE_FUNCTIONS_URL }}

      - name: Get latest tag
        id: get_tag
        run: |
          git fetch --tags
          echo "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_ENV

      - name: Upload to latest release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.tag }}
          file: build/app/outputs/flutter-apk/app-release.apk
          overwrite: true
